final List<Map<String, dynamic>> dummyProducts = [
  {
    'id': 'p1',
    'title': 'Organic Almond Milk',
    'price': 3.99,
    'imageUrl': 'assets/images/placeholder.jpg',
    'rating': 4.5,
    'inStock': true,
  },
  {
    'id': 'p2',
    'title': 'Vegan Protein Bar',
    'price': 2.49,
    'imageUrl': 'assets/images/placeholder.jpg',
    'rating': 4.2,
    'inStock': true,
  },
  {
    'id': 'p3',
    'title': 'Quinoa Pasta',
    'price': 4.99,
    'imageUrl': 'assets/images/placeholder.jpg',
    'rating': 4.7,
    'inStock': true,
  },
  {
    'id': 'p4',
    'title': 'Chia Seeds',
    'price': 5.99,
    'imageUrl': 'assets/images/placeholder.jpg',
    'rating': 4.8,
    'inStock': true,
  },
  {
    'id': 'p5',
    'title': 'Vegan Cheese Slices',
    'price': 3.49,
    'imageUrl': 'assets/images/placeholder.jpg',
    'rating': 4.1,
    'inStock': false,
  },
  {
    'id': 'p6',
    'title': 'Tofu Block',
    'price': 2.99,
    'imageUrl': 'assets/images/placeholder.jpg',
    'rating': 4.6,
    'inStock': true,
  },
  {
    'id': 'p7',
    'title': 'Vegan Mayonnaise',
    'price': 3.29,
    'imageUrl': 'assets/images/placeholder.jpg',
    'rating': 4.0,
    'inStock': true,
  },
  {
    'id': 'p8',
    'title': 'Plant-Based Nuggets',
    'price': 5.49,
    'imageUrl': 'assets/images/placeholder.jpg',
    'rating': 4.3,
    'inStock': false,
  },
  {
    'id': 'p9',
    'title': 'Oatmeal Cookies',
    'price': 2.79,
    'imageUrl': 'assets/images/placeholder.jpg',
    'rating': 4.4,
    'inStock': true,
  },
  {
    'id': 'p10',
    'title': 'Vegan Ice Cream',
    'price': 6.99,
    'imageUrl': 'assets/images/placeholder.jpg',
    'rating': 4.9,
    'inStock': true,
  },
  {
    'id': 'p11',
    'title': 'Coconut Yogurt',
    'price': 3.59,
    'imageUrl': 'assets/images/placeholder.jpg',
    'rating': 4.2,
    'inStock': true,
  },
  {
    'id': 'p12',
    'title': 'Vegan Jerky',
    'price': 4.29,
    'imageUrl': 'assets/images/placeholder.jpg',
    'rating': 3.9,
    'inStock': false,
  },
  {
    'id': 'p13',
    'title': 'Lentil Chips',
    'price': 2.99,
    'imageUrl': 'assets/images/placeholder.jpg',
    'rating': 4.0,
    'inStock': true,
  },
  {
    'id': 'p14',
    'title': 'Vegan Chocolate',
    'price': 3.99,
    'imageUrl': 'assets/images/placeholder.jpg',
    'rating': 4.7,
    'inStock': true,
  },
  {
    'id': 'p15',
    'title': 'Soy Milk',
    'price': 2.49,
    'imageUrl': 'assets/images/placeholder.jpg',
    'rating': 4.3,
    'inStock': true,
  },
  {
    'id': 'p16',
    'title': 'Vegan Granola',
    'price': 4.59,
    'imageUrl': 'assets/images/placeholder.jpg',
    'rating': 4.5,
    'inStock': true,
  },
  {
    'id': 'p17',
    'title': 'Cashew Butter',
    'price': 5.99,
    'imageUrl': 'assets/images/placeholder.jpg',
    'rating': 4.6,
    'inStock': false,
  },
  {
    'id': 'p18',
    'title': 'Vegan Pizza',
    'price': 7.99,
    'imageUrl': 'assets/images/placeholder.jpg',
    'rating': 4.8,
    'inStock': true,
  },
  {
    'id': 'p19',
    'title': 'Edamame Beans',
    'price': 2.29,
    'imageUrl': 'assets/images/placeholder.jpg',
    'rating': 4.1,
    'inStock': true,
  },
  {
    'id': 'p20',
    'title': 'Vegan Caesar Dressing',
    'price': 3.79,
    'imageUrl': 'assets/images/placeholder.jpg',
    'rating': 4.4,
    'inStock': true,
  },
];
