final List<Map<String, dynamic>> dummyProducts = [
  {
    'id': 'p1',
    'title': 'Organic Almond Milk',
    'price': 3.99,
    'imageUrl': 'https://via.placeholder.com/150?text=Almond+Milk',
    'rating': 4.5,
    'inStock': true,
  },
  {
    'id': 'p2',
    'title': 'Vegan Protein Bar',
    'price': 2.49,
    'imageUrl': 'https://via.placeholder.com/150?text=Protein+Bar',
    'rating': 4.2,
    'inStock': true,
  },
  {
    'id': 'p3',
    'title': 'Quinoa Pasta',
    'price': 4.99,
    'imageUrl': 'https://via.placeholder.com/150?text=Quinoa+Pasta',
    'rating': 4.7,
    'inStock': true,
  },
  {
    'id': 'p4',
    'title': 'Chia Seeds',
    'price': 5.99,
    'imageUrl': 'https://via.placeholder.com/150?text=Chia+Seeds',
    'rating': 4.8,
    'inStock': true,
  },
  {
    'id': 'p5',
    'title': 'Vegan Cheese Slices',
    'price': 3.49,
    'imageUrl': 'https://via.placeholder.com/150?text=Vegan+Cheese',
    'rating': 4.1,
    'inStock': false,
  },
  {
    'id': 'p6',
    'title': 'Tofu Block',
    'price': 2.99,
    'imageUrl': 'https://via.placeholder.com/150?text=Tofu',
    'rating': 4.6,
    'inStock': true,
  },
  {
    'id': 'p7',
    'title': 'Vegan Mayonnaise',
    'price': 3.29,
    'imageUrl': 'https://via.placeholder.com/150?text=Vegan+Mayo',
    'rating': 4.0,
    'inStock': true,
  },
  {
    'id': 'p8',
    'title': 'Plant-Based Nuggets',
    'price': 5.49,
    'imageUrl': 'https://via.placeholder.com/150?text=Nuggets',
    'rating': 4.3,
    'inStock': false,
  },
  {
    'id': 'p9',
    'title': 'Oatmeal Cookies',
    'price': 2.79,
    'imageUrl': 'https://via.placeholder.com/150?text=Oatmeal+Cookies',
    'rating': 4.4,
    'inStock': true,
  },
  {
    'id': 'p10',
    'title': 'Vegan Ice Cream',
    'price': 6.99,
    'imageUrl': 'https://via.placeholder.com/150?text=Vegan+Ice+Cream',
    'rating': 4.9,
    'inStock': true,
  },
  {
    'id': 'p11',
    'title': 'Coconut Yogurt',
    'price': 3.59,
    'imageUrl': 'https://via.placeholder.com/150?text=Coconut+Yogurt',
    'rating': 4.2,
    'inStock': true,
  },
  {
    'id': 'p12',
    'title': 'Vegan Jerky',
    'price': 4.29,
    'imageUrl': 'https://via.placeholder.com/150?text=Vegan+Jerky',
    'rating': 3.9,
    'inStock': false,
  },
  {
    'id': 'p13',
    'title': 'Lentil Chips',
    'price': 2.99,
    'imageUrl': 'https://via.placeholder.com/150?text=Lentil+Chips',
    'rating': 4.0,
    'inStock': true,
  },
  {
    'id': 'p14',
    'title': 'Vegan Chocolate',
    'price': 3.99,
    'imageUrl': 'https://via.placeholder.com/150?text=Vegan+Chocolate',
    'rating': 4.7,
    'inStock': true,
  },
  {
    'id': 'p15',
    'title': 'Soy Milk',
    'price': 2.49,
    'imageUrl': 'https://via.placeholder.com/150?text=Soy+Milk',
    'rating': 4.3,
    'inStock': true,
  },
  {
    'id': 'p16',
    'title': 'Vegan Granola',
    'price': 4.59,
    'imageUrl': 'https://via.placeholder.com/150?text=Granola',
    'rating': 4.5,
    'inStock': true,
  },
  {
    'id': 'p17',
    'title': 'Cashew Butter',
    'price': 5.99,
    'imageUrl': 'https://via.placeholder.com/150?text=Cashew+Butter',
    'rating': 4.6,
    'inStock': false,
  },
  {
    'id': 'p18',
    'title': 'Vegan Pizza',
    'price': 7.99,
    'imageUrl': 'https://via.placeholder.com/150?text=Vegan+Pizza',
    'rating': 4.8,
    'inStock': true,
  },
  {
    'id': 'p19',
    'title': 'Edamame Beans',
    'price': 2.29,
    'imageUrl': 'https://via.placeholder.com/150?text=Edamame',
    'rating': 4.1,
    'inStock': true,
  },
  {
    'id': 'p20',
    'title': 'Vegan Caesar Dressing',
    'price': 3.79,
    'imageUrl': 'https://via.placeholder.com/150?text=Caesar+Dressing',
    'rating': 4.4,
    'inStock': true,
  },
];
